# Generated by Django 3.2.8 on 2021-11-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211031_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='invite_id',
        ),
    ]
