version: '3.5'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
    - ./data/postgres_db:/var/lib/postgresql/data
    env_file:
      - koji/db.env
  
  web:
    build: .
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - koji/web.env
    depends_on:
      - db
