version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
    - ./data/postgres_db:/var/lib/postgresql/data
    environment:
    - DB_NAME = "${DATABASE_NAME}"
    - DB_USER = "${DATABASE_USER}"
    - DB_PW = "${DATABASE_PASS}"
  
  web:
    build:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - : '8000:8000'
    env_file:
      - koji/.env
    depends_on:
      -db
volumes:
  postgres_data: