version: '3.5'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    container_name: koji_db
    networks:
        - koji_db_network
        - koji_web_network
    volumes:
    - ./data/postgres_db:/var/lib/postgresql/data
    env_file:
      - koji/db.env
  
  web:
    build: .
    container_name: kojiapi
    restart: always
    volumes:
        - koji_static_volume:/usr/src/app/static
    networks:
        - koji_web_network
        - koji_db_network
    env_file:
      - koji/web.env
    depends_on:
      - db


volumes:
    koji_static_volume:
        external: true


networks:
    koji_web_network:
        external: true

    koji_db_network:
        external: true
